[[headers]]
  for = "/Build/WebGlCustom.loader.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/Build/WebGlCustom.framework.js.br"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Encoding = "br"

[[headers]]
  for = "/Build/WebGlCustom.data.br"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Encoding = "br"

[[headers]]
  for = "/Build/WebGlCustom.wasm.br"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Encoding = "br"
